# Generated by Django 3.1.4 on 2021-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='zipcode',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
