# Generated by Django 3.1.4 on 2021-01-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_checkout_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.checkout', verbose_name='Produktart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONWAY', 'On the Way'), ('DONE', 'Done')], default='PENDING', max_length=50),
        ),
    ]
