# Generated by Django 3.1.4 on 2021-01-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210112_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.checkout', verbose_name='Checkout Details'),
        ),
    ]
