# Generated by Django 3.1.4 on 2021-01-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='userprofile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
