# Generated by Django 3.0.1 on 2020-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
