# Generated by Django 3.0.1 on 2020-01-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cnthead0',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='cnthead1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='cnthead2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='head0',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='head1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='head2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
