# Generated by Django 3.0.1 on 2020-01-17 20:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cnthead0',
            field=tinymce.models.HTMLField(),
        ),
    ]
