# Generated by Django 3.0.1 on 2020-01-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200118_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cnthead0',
            field=models.TextField(default=''),
        ),
    ]
