# Generated by Django 3.0.1 on 2020-01-17 21:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200118_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cnthead0',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
